config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"
  resources :blogs

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete 'logout', to: 'sessions#destroy'
  get "about_me", to: 'about#show'

  resources :email, only:[:create]
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/email.rb
class Email
  attr_reader :name, :email_address, :subject, :message

  def initialize(name, email_address, subject, message)
    @name = name
    @email_address = email_address
    @subject = subject
    @message = message
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  helper_method :current_user
  include ActionView::Helpers::TextHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def new
    if current_user
      @blog = Blog.new
    else
      redirect_to root_path
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def index
    @blogs = Blog.all.reverse
  end

  def edit
    if current_user
      @blog = Blog.find(params[:id])
    end
  end

  def create
    if current_user
      @blog = Blog.new(blog_params)
      @blog.save
      redirect_to blog_path(@blog)
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body)
  end

end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def create
    @email = Email.new(params[:name], params[:email], params[:subject], params[:message])
    UserNotifier.send_contact_email(@email).deliver_now
    flash[:message] = "Thank you! Your email has been sent."
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @blog = Blog.last
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to new_blog_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/about/show.html.erb
<div class="container wrapper first" id="top">
  <h1>About Me</h1>

  <p>*Note: This is a hypothetical interview I conducted with myself.  I have always wanted to be interviewed by Rolling Stone, this is probably the closest I will ever come to it. </p>

  <p>Interviewer: “Hi Mihir! Thank you so much for taking the time to join me today.  We have been looking forward to this interview for a long time.”</p>

  <p>Me: “No, thank you so much for having me. The pleasure is all mine.”</p>

  <p>Interviewer: “So let’s jump right into it.”</p>

  <p>Me: “Cool, let’s do it!”</p>

  <p>Interviewer: “I heard you grew up in Seattle, tell me a bit about life in the 2-0-6?”</p>

  <p>Me: “Yes, I am in fact a Seattle guy.  I grew up on Mercer Island, a suburb right outside of the city.  It was a fairly small and close-knit community. Most of us on the Island went to middle and  high school together so I made a lot of lifelong friends.  All of us are still really close to this day. Oh yeah, I forgot to mention GO SEAHAWKS! Watch us comeback better than ever this year!”</p>

  <p>Interviewer: “I agree with you, I think the Seahawks are going to make another Superbowl run this year.  So Mihir, tell me a bit about your higher education?”</p>

  <p>Me: “I did my undergrad at the University of Washington in Seattle. I earned my Bachelors in Science in Molecular, Cellular, and Developmental Biology and completed all Pre-Med requirements.  I had an awesome experience at the University of Washington.  In addition to my academic endeavors, I sang in A Capella group, conducted epilepsy research, and attended every single Husky football game...even the season we went winless, that was true commitment.”</p>

  <p>Interviewer: “What did you do after graduating?”</p>

  <p>Me: “I worked in clinical vaccinology.  I assisted with executing clinical trials that would assess the effectiveness of vaccines. I actually worked on the study that analyzed the quality of the annual flu vaccine.  After a year and half of that I got accepted into medical school in Denver.”</p>

  <p>Interviewer: “So how did you make the transition from medicine to software?”</p>

  <p>Me: “My senior year of college I took Computer Science 142 with Stuart Reges as one of my electives.  I had always loved computers growing up and I wanted to learn more about this “code” thing everyone spoke of.  This one class changed my life.  I got a taste of the power code has on solving human problems, my mind was truly blown! However, the reality was that I was a senior in college and had already taken my MCATs, it felt like it was too late to switch.  As I started medical school, I always had programming in the back of my mind.  I can say for a fact that I did not hate medicine, I just liked programming more.  As I was sitting in class one day surfing tech blogs, I came across Turing School of Software and Design.  Turing provided the opportunity for people like me to learn the necessary skills to become a programmer without having to go back for another Bachelor's degree.  All of sudden, I realized that it wasn’t too late.  Soon after I made the decision to make a career change.”</p>

  <p>Interviewer: “What experiences from your background in healthcare and medicine can you bring to software development?”</p>

  <p>Me: “A strong medical diagnosis is rooted in extracting the correct information from the patient.  That means the physician has to ask precise questions and listen to the patient carefully.  Learning this skill has proven to be extremely valuable in the dev world. Having the ability to grasp an understanding of the human problem I am trying to solve and the technical challenges I may encounter before I start coding, helps me write cleaner code.  In medicine, you can prescribe medications to treat every possible differential diagnosis, but that should never be the case if you asked the correct questions.  Yes the patient may get better by taking 5 different drugs but it's not good for the patient’s long-term health.  The same applies for code.  You can manage to get something working by writing sloppy, functional code but you are compromising its long-term viability.”</p>

  <p>Interviewer: “Awesome, that is an interesting perspective.  Let us conclude this interview with a lighter question.  What do you do for fun outside the realm of code?”</p>

  <p>Me: “Haha, I guess you were saving this hard-hitting question for the end.  Well, I guess I have to start with sports.  I love playing and watching sports.  I have a black belt in Tae Kwon Do and I play competitive tennis and ping-pong .  I also have been know make appearances at my local park to participate in some pick up sports. I must mention that one of my greatest achievements is that I am a multiple-time fantasy football champion.  In terms of non-sports related hobbies, I am really into cooking, traveling, Indian classical music, and wikipediaing.”</p>

  <p>Interviewer: “Thanks for your time Mihir and best of luck to you.”</p>

</div>

app/views/blogs/edit.html.erb
<div class="container wrapper first" id="top">

<h1>Edit Blog Post</h1>
<%= form_for(@blog, url: blog_path, method: "PUT") do |f| %>
  <ul>
  <% @blog.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>
</div>

app/views/blogs/index.html.erb
<div class="container blogpage">
<% @blogs.each do |blog| %>
  <div class="blogitem">
    <h2><%= blog.title %></h2>
    <p class="blogbody"><%= blog.body.html_safe %></p>
    <% if current_user %>
      <p class="blogbody"><%= link_to "Edit Blog", edit_blog_path(blog), method: "get" %></p>
    <% end %>
  </div>
<% end %>
</div>

app/views/blogs/new.html.erb
<div class="container wrapper first" id="top">

<h1>Create a New Blog Post</h1>
<%= form_for(@blog, html: {multipart: true}) do |f| %>
  <ul>
  <% @blog.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>
</div>

app/views/blogs/show.html.erb
<div class="container wrapper first" id="top">
  <h1><%= @blog.title %></h1>
  <p><%= @blog.body.html_safe %></p>
</div>

app/views/home/show.html.erb

		<!-- Home -->
			<div class="wrapper style1 first">
				<article class="container" id="top">
					<div class="row">
						<div class="4u 12u(mobile)">
							<span class="image fit"><%= image_tag "mihir_parikh.jpg" %></span>
						</div>
						<div class="8u 12u(mobile)">
							<header>
								<h1>Hi. I'm <strong>Mihir Parikh</strong>.</h1>
							</header>
							<a href="/about_me" class="button big scrolly">More About Me</a>
						</div>
					</div>
				</article>
			</div>

		<!-- recent blog post -->
			<div class="wrapper style2">
				<article id="work">
					<header>
						<h1>Most Recent Blog Post</h1>
					</header>
					<div class="container">
					  <h2 class="center"><%= @blog.title %></h1>
						<div align="left">
					  	<p><%= @blog.body.html_safe %></p>
						</div>

				</article>
			</div>

		<!-- Portfolio -->
		<div class="wrapper style2">
			<article id="work">
				<header>
					<h2>Recent Projects</h2>
				</header>
				<div class="container">
					<div class="row">
						<div class="grid">
							<section class="box style1">
								<%= link_to image_tag("bizzspot.png", class:"projectimg"), "http://bizzspot.herokuapp.com/", target: "_blank" %>
								<h3>BizzSpot</h3>
								<p>Aggregates and visualizes demographic data and accessability of a given location.</p>
							</section>
						</div>
						<div class="grid">
							<section class="box style1">
								<%= link_to image_tag("marvelus.png", class:"projectimg"), "http://marvel-us.herokuapp.com/", target: "_blank" %>
								<h3>Marvelus.us</h3>
								<p>Analyzes tweets to match users with a superhero.</p>
							</section>
						</div>
					</div>
					<div class="row">
						<div class="grid">
							<section class="box style1">
								<%= link_to image_tag("hipsterbytes.png", class:"projectimg"), "http://hipsterbytes.herokuapp.com/", target: "_blank" %>
								<h3>Hipster Bytes</h3>
								<p>E-commerce site: select items, add to cart, and checkout.</p>
							</section>
						</div>
						<div class="grid">
							<section class="box style1">
								<%= link_to image_tag("phonatics.png", class:"projectimg"), "http://phonatic.herokuapp.com/", target: "_blank" %>
								<h3>Phonatics</h3>
								<p>Pivoted Hipster Bytes into a multi-tenant stock photography site.</p>
							</section>
						</div>
					</div>
				</div>
			</article>
		</div>

		<!-- Contact -->
			<div class="wrapper style4">
				<article id="contact" class="container 75%">
					<header>
						<h2>Contact Me</h2>
					</header>
					<div>
						<div class="row">
							<div class="12u">
								<form action="/email" method="post">
									<div>
										<div class="row">
											<div class="6u 12u(mobile)">
												<input type="text" name="name" id="name" placeholder="Name" />
											</div>
											<div class="6u 12u(mobile)">
												<input type="text" name="email" id="email" placeholder="Email" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<input type="text" name="subject" id="subject" placeholder="Subject" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<textarea name="message" id="message" placeholder="Message"></textarea>
											</div>
										</div>
										<div class="row 200%">
											<div class="12u">
												<ul class="actions">
													<li><input type="submit" value="Send Message" /></li>
													<li><input type="reset" value="Clear Form" class="alt" /></li>
												</ul>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</article>
			</div>

		<!-- Scripts -->

			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mihirparikh</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
  <link rel="stylesheet" href="assets/css/main.css" />
  <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
  <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
  <nav id="nav">
    <ul class="container">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Previous Blog Posts", blogs_path %></li>
      <li><%= link_to "My GitHub", 'https://github.com/mihir787', target: "_blank"%></li>
      <li><%= link_to "LinkedIn", 'https://www.linkedin.com/in/mihirsparikh', target: "_blank"%></li>
      <% if current_user %>
        <li><%= link_to "Logout", logout_path, method: 'DELETE' %></li>
      <% end %>
    </ul>
  </nav>

  <div class="flashes">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/user_notifier/send_contact_email.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>
      <%= @email.message %>
    </p>
    <p>
      <%= @email.name %>
    </p>
  </body>
</html>